### ISSUE TITLE
replace twitter icon with an X

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter-ui#100]
![CleanShot 2023-12-07 at 16 29 47@2x](https://github.com/micronaut-projects/micronaut-starter-ui/assets/864788/bef1d59c-6f9d-4794-8a56-19b2f3ce1d8c)

**Comment by timyates** [comment]
https://upload.wikimedia.org/wikipedia/commons/5/53/X_logo_2023_original.svg
