### ISSUE TITLE
ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by osscontributor** [micronaut-projects/micronaut-starter-ui#102]
I am currently seeing ERR_CERT_DATE_INVALID in the console when a request is made to next.micronaut.io/versions.

<img width="1284" alt="Screenshot 2023-12-20 at 9 49 00 AM" src="https://github.com/micronaut-projects/micronaut-starter-ui/assets/15482/ec576804-0dc2-4390-8c8d-0bdd2a9ea985">

**Comment by sdelamo** [comment]
I don't think next.micronaut.io is used for anything.
