### ISSUE TITLE
Update UI to support Push to GitHub

### ISSUE THREAD

**Issue by JasonTypesCodes** [micronaut-projects/micronaut-starter-ui#13]
See: https://github.com/micronaut-projects/micronaut-starter/pull/495

**Comment by pgressa** [comment]
Here are some details for the UI implementation. The flow follows https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps. So the React UI should in case the user hits Push to GitHub:
- redirect user to: `https://github.com/login/oauth/authorize?client_id=[CLIENT-ID]&scope=user,repo&redirect_uri=https://launch.micronaut.io/github/[APPLIATION-TYPE/[APPLICATION-NAME]&[...]state=[unguessable random string]`

The repository name is derived from the application name. In case the repository already exists then request fails. In case repository doesn't exists, the json with:
- `clone_url` - link that can be used to generate `git clone <url>` command so user can just copy/paste it and run
- `html_url` - link to github html
- `url` - api url

These fields are taken from the repository GitHub create repository request https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-repository-for-the-authenticated-user
