### ISSUE TITLE
Start Over Doesn't Reset Form

### ISSUE THREAD

**Issue by jeffbrown** [micronaut-projects/micronaut-starter-ui#19]
After I download a .zip archive I am presented with a dialog that includes "CLOSE" and "START OVER" as options.  I think "START OVER" is supposed to reset the form fields but that does not appear to be working.  Tested in Chrome 87.0.4280.67 (Official Build) (x86_64).

<img width="843" alt="Screen Shot 2020-11-30 at 2 19 52 PM" src="https://user-images.githubusercontent.com/15482/100661641-5cdb3180-3319-11eb-832a-625dcb2b3e61.png">

**Comment by JasonTypesCodes** [comment]
I feel when "Start Over" is selected it should reset everything back to the default

**Comment by timyates** [comment]
I believe this was fixed here https://github.com/micronaut-projects/micronaut-starter-ui/commit/6e721887f6da498acc489c4336d5dbeca1c82abd

For me everything apart from the chosen micronaut version resets
