### ISSUE TITLE
Dark Mode Features/Diff/Preview Modals Need Border

### ISSUE THREAD

**Issue by JasonTypesCodes** [micronaut-projects/micronaut-starter-ui#26]
We either need to add a border to these modals or change the background color of the modal to add a contrast between the modal and the application background:

![image](https://user-images.githubusercontent.com/1888131/107093457-e05a4880-67ca-11eb-9618-9a189e7bc77a.png)

**Comment by eahrold** [comment]
Hah. Another design oversight, the shadow is black that would show on a not pure black bg.

**Comment by JasonTypesCodes** [comment]
Closed by #29
