### ISSUE TITLE
Update text in buttons to be uppercase

### ISSUE THREAD

**Issue by JasonTypesCodes** [micronaut-projects/micronaut-starter-ui#28]
Please update the font in the buttons (Features, Diff, Preview, Generate) to be uppercase

**Comment by eahrold** [comment]
It was specifically called in the design notes to make them capitalized. Do we want to revert that back to uppercase?

**Comment by JasonTypesCodes** [comment]
I'll double check

**Comment by JasonTypesCodes** [comment]
I've confirmed that this should go back to uppercase :)
