### ISSUE TITLE
Add keyboard shorcuts to launch

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter-ui#5]
Wish list: 

- `?` = Show Keyboard Short cut help
- Shortcut for every button (Features, Diff, Preview, Generate Project) 
   Generate project = `CMD + Return `seems like the best option. 
- Shortcut to change language
- Shortcut to change build
- Shortcut to change test framework

**Comment by eahrold** [comment]
Going to bring this feature along for the ride with
https://github.com/micronaut-projects/micronaut-starter-ui/pull/1

Since they're both heavily related to keyboard event handling.

**Comment by JasonTypesCodes** [comment]
Added in 2.3.2
