### ISSUE TITLE
Add share link to  micronaut launch 

### ISSUE THREAD

**Issue by eisig** [micronaut-projects/micronaut-starter-ui#8]
Add share link to  https://micronaut.io/launch/. like https://start.spring.io/

1.  for  share project template
2. for  report some issue, just paste the link to show how it's created.

**Comment by sdelamo** [comment]
I think we should move this to starter-ui repo. I think it is a 100% front end feature.

**Comment by ilopmar** [comment]
@sdelamo I already moved to starter-ui

**Comment by eahrold** [comment]
I'll include this capability here.

```
It would be nice to be able to permalink to a file in preview, something like:

https://micronaut.io/launch#/preview/DEFAULT/demo?path=build.gradle
```

https://github.com/micronaut-projects/micronaut-starter/issues/494#issue-713376235

**Comment by JasonTypesCodes** [comment]
Added in 2.3.2
