### ISSUE TITLE
Disable app name equals micronaut in the ui

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter-ui#9]
using `micronaut` as an app name causes issues. See: 

https://github.com/micronaut-projects/micronaut-starter/issues/352

`micronaut` will no longer be a valid name. We are adding the validation on the server side: 

https://github.com/micronaut-projects/micronaut-starter/pull/403

But we should validated it on the UI as well.

**Comment by JasonTypesCodes** [comment]
I believe this is already functioning correctly

![image](https://user-images.githubusercontent.com/1888131/100663906-89dd1380-331c-11eb-8d8c-4a83e0c84c66.png)
